name: Build and Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*.*.*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get release tag
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Cosmos
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            gotocompany/cosmos:latest
            gotocompany/cosmos:${{ steps.get_version.outputs.version-without-v }}
      - name: Build and Push Cube
        uses: docker/build-push-action@v2
        with:
          context: ./cube-server
          push: true
          tags: |
            gotocompany/cosmos-cube:latest
            gotocompany/cosmos-cube:${{ steps.get_version.outputs.version-without-v }}
